[package]
name = "rustfft-jl"
version = "0.1.0"
edition = "2021"
authors = ["Thomas van Doornmalen <thomas.vandoornmalen@gmail.com>"]
description = "Julia binding library for RustFFT"
homepage = "https://github.com/Taaitaaiger/rustfft-jl"
repository = "https://github.com/Taaitaaiger/rustfft-jl"
readme = "./README.md"
keywords = ["Julia", "fft", "fourier", "transform", "ffi"]
categories = ["api-bindings", "mathematics"]
license = "MIT"
rust-version = "1.65"

[features]
julia-1-6 = ["jlrs/julia-1-6"]
julia-1-7 = ["jlrs/julia-1-7"]
julia-1-8 = ["jlrs/julia-1-8"]
julia-1-9 = ["jlrs/julia-1-9"]
julia-1-10 = ["jlrs/julia-1-10"]
i686 = ["jlrs/i686"]
windows = ["jlrs/windows"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
rustfft = "6"
jlrs = { version = "0.18", git = "https://github.com/Taaitaaiger/jlrs", rev = "a2342e5", features = ["ccall", "jlrs-derive", "uv", "no-link"] }
